steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/white-smile-408100/asr-landing-page', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/white-smile-408100/asr-landing-page']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'asr-landing-page', '--image', 'gcr.io/white-smile-408100/asr-landing-page', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/white-smile-408100/asr-landing-page